EXAMPLE_IMG_PATH    = 'logs/images/processing/240725_123456.jpg'
EXAMPLE_MAP_PATH    = 'logs/images/processing/map.png'
NULL_IMG_PATH       = 'assets/null.png'
MAIN_UI_PATH        = 'UI/main.ui'
CONFIGS_PATH        = 'src/configs.json'